User Authentication
bilalrajput09/Budget-App pull request #1
Opened 2023-08-23 10:40 UTC by bilalrajput09

I build the welcome page.
Add devise and authentication system.
Add stylings.

2023-08-24 20:17 UTC, mckent05 requested changes
Hi @bilalrajput09, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- You have done well creating your budget application, 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-24 20:17 UTC, mckent05 commented on app/controllers/categories_controller.rb
> +  end
- You have done well so far, but in order to properly validate your input, I think you should use strong params. i.e `params.require(:attribute_name).permit(:name, icon)`. Please fix this for both `category_params` and `spending_params` 😄

2023-08-24 20:17 UTC, mckent05 commented on app/controllers/categories_controller.rb
> +    if current_user.spendings << spending
**OPTIONAL** - Good job done so far, but to make your code easier to read and implement the `belongs-to` relationship between spending and user i suggest you do: 
```ruby
spending = current_user.spending.new(spending_params)
```

2023-08-24 20:17 UTC, mckent05 commented on app/views/categories/show.html.erb
> +<%= render "categories/button_category_spendings"%>
- You have done well so far, but according to the project requirements, to add a new transaction:

```
The user fills out a form to create a new transaction with:

* name (mandatory)
* amount (mandatory)
* categories (mandatory at least one)
```
I suggest you make it possible for the user to choose one or more `category` for the new transaction and not automatically the category that was clicked on. Please fix this 🙏

2023-08-24 20:17 UTC, mckent05 commented on spec/integration/spendings_spec.rb
> +end
- Good job done so far, but you have not properly done your integration tests. Remember integration test should ensure that your rendered template contains the right information filled in from the database. Please fix this 👍. You can use this [article](https://semaphoreci.com/community/tutorials/integration-testing-ruby-on-rails-with-minitest-and-capybara) as a reminder.

2023-08-24 20:17 UTC, mckent05 commented on spec/integration/spendings_spec.rb
> +end
- Good job done so far, but you have not properly done your integration tests. Remember integration test should ensure that your rendered template contains the right information filled in from the database. Please fix this 👍. You can use this [article](https://semaphoreci.com/community/tutorials/integration-testing-ruby-on-rails-with-minitest-and-capybara) as a reminder.

2023-08-24 20:17 UTC, mckent05 commented on README.md
> +<a href="#">Demonstration video</a>
- According to the project requirements, your documentation should contain a video presentation, the presentation should contain the following:
```
1. The student recorded a video presenting the features of the project.
1. The maximum length of the video is 5 minutes.
1. The video contains a clear and objective description about the project in professional English. The topic and purpose of the project are made clear.
1. The video contains a demo of the project, highlighting all the project features.
1. The video contains a highlight about a piece of the code the student finds interesting or is proud of making.

> **Note:** It's recommended that students use [Loom](https://www.loom.com/) to record to video but they can use any tool they want as long as they share an online link of the uploaded video.

```

2023-08-25 10:48 UTC, VICTOR-CHUKWU requested changes
Hi @bilalrajput09 , 

## STATUS: CHANGES REQUIRED :recycle: 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Suggested changes
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-08-25 10:48 UTC, VICTOR-CHUKWU commented on app/views/categories/show.html.erb
> +<%= render "categories/button_category_spendings"%>
- [ ] When I did not fill out any of the mandatory fields, it threw an error, this is not user-friendly at all, you can add a flash message telling the user to fill in the input missing, or simply do not allow submit of form when all fields are not filled
![Screenshot from 2023-08-25 11-38-09](https://github.com/bilalrajput09/Budget-App/assets/66097371/b38f873b-8906-4487-b62a-db90058be564)

2023-08-25 12:22 UTC, mukhammadrizooff approved these changes
Hi @bilalrajput09, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

<img src="https://media4.giphy.com/media/sR9nilEznDoSlga667/giphy.gif"/> 

## Highlights
- No linter errors ✔️ 
- Correct GitFlow ✔️ 
- Good implementations ✔️
- Descriptive `README` file ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-25 12:31 UTC, merged